### ISSUE TITLE
It doesn't recurse Active Directory Groups

### ISSUE THREAD

**Issue by diablo581** [tmunzer/mist_ldap_sync#1]
The current code based doesn't recurse groups in Active Directory.  If you change one line in mist_ldap.py you can have it do that though.

41c41
<                 "(&(objectclass=person)(memberOf={0}))".format(self.search_group),
---
>                 "(&(objectclass=person)(memberOf:1.2.840.113556.1.4.1941:={0}))".format(self.search_group),

**Comment by tmunzer** [comment]
Hi,

This had been added. It's not enabled by default and requires a new config parameter "LDAP_RECURSIVE_SEARCH=True".
Can you give it a try?

Thanks,

**Comment by diablo581** [comment]
This seems to be working as intended. Thanks!
