### ISSUE TITLE
Emails not sent to users

### ISSUE THREAD

**Issue by tmunzer** [tmunzer/mist_ldap_sync#10]
@tmunzer after implementing this code I am not able to send emails anymore when passcode creation is greater than 1k at least. I haven't tested much yet as I am just now discovering this and am out of time today to test it. Also, is there a way to run the script to re-email users their passcodes? An argument for all users as well as feeding an individual user to be re-emailed would be SUPER helpful.

_Originally posted by @JuggernautKY in https://github.com/tmunzer/mist_ldap_sync/issues/8#issuecomment-1819813055_

**Comment by tmunzer** [comment]
I applied a fix. The latest version was not sending the user emails, this should now be fixed.
I also added the "-r" / "--resend-emails" to just send the emails for all the already created PSKs.
Be aware there may be some issue with some SMTP server, and they may drop the requests if there are too many of them.

I'll add an option to let Mist send the email directly, this will remove the need to use an external SMTP server.

**Comment by tmunzer** [comment]
I added a setting in the env file to let Mist send the PSK email to users.
This requires the `MIST_PSK_EMAIL = True` in the environment file.

**Comment by JuggernautKY** [comment]
My apologies, I will create a new issue next time. Thank you for this, does
the resend option resend to all or is there a way to specify a user or
user's to resend to?

**Comment by tmunzer** [comment]
no problem. 

I just added another option load a CSV file with the list of user email addresses to whom the psk should be resent.

```
-r, --resend-emails Resend PSK emails to users. This option disable to PSK
                    creation and deletion (will just generate and send the 
                    emails)
                    This option DOES NOT work with Mist Emails
-f, --file=         if -r/--resend-emails, location of a CSV file with the list
                    of emails to whom the psk should be resend
```

**Comment by JuggernautKY** [comment]
Awesome, thanks!


*Cory Goode*
*Network Administrator*Barren County Technology Office
511 Trojan Trail
Glasgow, KY 42141
*office* (270) 659-2875 *or* 25981

Click Here to use the Safe Schools online reporting tool
<https://homelandsecurity.ky.gov/SafeSchools/Pages/default.aspx>

**Comment by JuggernautKY** [comment]
clarification... the resend option doesn't work with mist emails or the file option?

**Comment by tmunzer** [comment]
Sorry, i'll improve the test...

The resend option doesn't work with Mist emails (when using Mist to send the emails, the email in only sent when the PSK is created or modified). 

Mist emails > no resend option
Custom SMTP > resend option, with or without the -f option

**Comment by JuggernautKY** [comment]
Thank you. I will be testing this soon and let you know the results! 👍

**Comment by JuggernautKY** [comment]
There appears to be an issue with line 157 that produces this error. 

`File "E:\Scripts\mist-test\mist_ldap_sync.py", line 157, in _load_mist
    "psk_email": eval(os.environ.get("MIST_PSK_EMAIL", False)),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object`

Removing the eval() to make the line read `"psk_email": os.environ.get("MIST_PSK_EMAIL", False),` appears to resolve that issue.  However, then there is another error, `File "E:\Scripts\mist-test\mist_ldap_sync.py", line 436, in _send_user_email
    (self.resend_emails and user.get("email") in self.resend_emails_filter) or
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`. I haven't determine any work around or fix for this. I also have created a branch to add an option to allow the use of multiple templates. I think I have that working but obviously can't test without resolution of these two issues. Please review and advise, thanks so much for all of your help!

P.S.: My command to run the string is as follows, `python mist_ldap_sync.py -e Barren.env -r -f user.txt`, executed from the directory where all the files are located.

**Comment by JuggernautKY** [comment]
My second error was due to my file being named users.txt.

**Comment by tmunzer** [comment]
Thanks @JuggernautKY , there was an issue on the default value for MIST_PSK_EMAIL setting. This is now fixed.

And regarding the second point, I'll see to add a test to check if the file actually exists or not.
