### ISSUE TITLE
Users being added and deleted over and over

### ISSUE THREAD

**Issue by JuggernautKY** [tmunzer/mist_ldap_sync#12]
I have about 30-40 users that are being added and deleted in a cycle each time the script runs. They seem to be broken up into two groups one of 8 users and one of 28 users that on one run it will delete the 8 and add the 28. Then the next time it runs it will delete the 28 and add the 8. All of the users are in the group and one of the users I have been looking at closer to try to determine the cause is in the log file that lists all of the users found in the LDAP query. However, on that run the script when ran in dry-run mode states it would delete this user. Any assistance would be greatly appreciated.

Thank you!

**Comment by tmunzer** [comment]
Hi,

My thought is for any reason the PSK is created with a different name from what the script is getting from the LDAP.
Is there any special characters in the user names? or maybe the generated name is too long and truncated in Mist?

If it's ok for you, can you share the script log file so I can dig in. You can send it to me by email: tmunzer at juniper.net

Thanks

**Comment by tmunzer** [comment]
fixed
