### ISSUE TITLE
VLAN Tags

### ISSUE THREAD

**Issue by diablo581** [tmunzer/mist_ldap_sync#2]
Would it be possible to have a configuration option to set VLAN tag for the PPSK?

I am not sure where in the code to put that in.

**Comment by tmunzer** [comment]
Hi, 

This had beed added. Can you give it a try (it requires a new config parameter "MISY_PSK_VLAN"

Thanks.

**Comment by diablo581** [comment]
Just ran a check, and it wasn't working, but then I went back and looked and there is a typo in the example.env

MISY_PSK_VLAN=10

should be

MIST_PSK_VLAN=10

**Comment by diablo581** [comment]
After fixing this and testing VLAN tagging seems to be working correctly
