### ISSUE TITLE
Possible --dry-run option?

### ISSUE THREAD

**Issue by diablo581** [tmunzer/mist_ldap_sync#3]
The -c option works good for checking to make sure you have your script options correct, but it doesn't let you know what would happen if you were to run the script.

Would it be possible to add a dry-run option so that you can see what would happen if you were to run it? That way you can check for other errors.  Like I know I mistyped the name of my group and running the script deleted all my PSKs.  Once I fixed that then it had to recreate all of them.

Would be nice to be able to run it without making the changes happen since we now have people using the existing PSKs.

Or maybe an option that tells it not to delete anything?

**Comment by tmunzer** [comment]
Hi, I just added a -d / --dry-run option.
It will execute all the tasks, but will not create/delete PPSKs, and will not send any email.

**Comment by diablo581** [comment]
Looks good man. Thank you!

I think we have got this into a shape that I am going to start running it nightly to sync multiple things.

Thanks for the work!
