### ISSUE TITLE
Error when trying to pass a config file with -e

### ISSUE THREAD

**Issue by diablo581** [tmunzer/mist_ldap_sync#5]
When I try to pass the script a specific configuration file I am getting the following error:

`Traceback (most recent call last):
  File "/home/brent/mist_ldap_sync/mist_ldap_sync.py", line 366, in <module>
    main()
  File "/home/brent/mist_ldap_sync/mist_ldap_sync.py", line 351, in main
    load_dotenv(dotend_path=env_file)
TypeError: load_dotenv() got an unexpected keyword argument 'dotend_path'
`

If I take the same file and name it .env then it works.  Looking at the code I am not sure what the error might be related to.

**Comment by diablo581** [comment]
Found it. Typo. Pushed into my branch and created a pull request.

**Comment by tmunzer** [comment]
yes, you were quicker than me! :)
Thanks!
