### ISSUE TITLE
Potential Issue, Pagination on API call for existing PSKs

### ISSUE THREAD

**Issue by diablo581** [tmunzer/mist_ldap_sync#7]
Was reading this section of the API documentation and noticed this:

```
Get PSK
**Get list of psks on the org. This API is always paginated, default limit is 100.**

Use query param, to filter or sort by name/role/ssid

GET /api/v1/orgs/:org_id/psks?name=Common&role=student&sort=ssid&limit=200&page=3
```

Which makes me wonder if when I start putting 1000 psks in there, if I pull someone out of the group that is on page 5 is the script going to see it  or will it miss it?

It looks like you can add a limit option to the request and I know the APs can't handle more than 5000 PSKs do you think there is merit to adding something like that to the Request URL?

**Comment by tmunzer** [comment]
Hi, 

I just updated the code. I didn't touch this script for a while, this is why it didn't took care of the pagination.
The script is now requesting a list of 1000 PPSKs by default, and will request additional pages if there is more than 1000 PPSKs.

You can validate the behavior by changing the `limit` value in the mist_psk.py file:
```python3
# Default:
        response = mist_get(self.apitoken, url, query={"ssid": self.ssid}, limit=1000)
# Easy Test, requesting 1 PPSK at a time:
        response = mist_get(self.apitoken, url, query={"ssid": self.ssid}, limit=1)
```

You can display the requested URLs by uncommenting the line `print("\r\nnRequest > GET %s" % final_url)` in the file req.py (line 40).

Exemple:
```
❯ python3 ./mist_ldap_sync.py -d


Python Script to Syncronize LDAP users and Mist PSK.
Written by Thomas Munzer (tmunzer@juniper.net)
Github: https://github.com/tmunzer/mist_ldap_sync


Loading LDAP settings .........................................................✔
Loading MIST settings .........................................................✔
Loading SMTP settings .........................................................✔
______________________________________INIT______________________________________

__________________________________LDAP SEARCH___________________________________
Contacting LDAP server on xxxxxxxx:389 (SSL: False) ........................✔
Executing LDAP search .........................................................✔
Processing LDAP accounts ......................................................✔

__________________________________MIST REQUEST__________________________________
Requesting api.eu.mist.com to get the list of PSKs ............................
nRequest > GET https://api.eu.mist.com/api/v1/orgs/39ce2088-xxxx-xxxx-xxxx-1a5a88bab5ee/psks?ssid=Mist-Live-BYOD&limit=1&page=1

nRequest > GET https://api.eu.mist.com/api/v1/orgs/39ce2088-xxxx-xxxx-xxxx-1a5a88bab5ee/psks?ssid=Mist-Live-BYOD&limit=1&page=2

nRequest > GET https://api.eu.mist.com/api/v1/orgs/39ce2088-xxxx-xxxx-xxxx-1a5a88bab5ee/psks?ssid=Mist-Live-BYOD&limit=1&page=3

nRequest > GET https://api.eu.mist.com/api/v1/orgs/39ce2088-xxxx-xxxx-xxxx-1a5a88bab5ee/psks?ssid=Mist-Live-BYOD&limit=1&page=4

nRequest > GET https://api.eu.mist.com/api/v1/orgs/39ce2088-xxxx-xxxx-xxxx-1a5a88bab5ee/psks?ssid=Mist-Live-BYOD&limit=1&page=5
✔

_______________________________ DRY RUN - DELETE________________________________
User test1 not found... Removing the psk ......................................✔
User test2 not found... Removing the psk ......................................✔
User test3 not found... Removing the psk ......................................✔
User test4 not found... Removing the psk ......................................✔
User test5 not found... Removing the psk ......................................✔

_______________________________ DRY RUN - CREATE________________________________
New User detected --------------------------------------------------------------
    name : tmunzer@stag.one
    email: tmunzer@stag.one
    Creating the PPSK for user ................................................✔
    Sending the email .........................................................✔

_____________________________________REPORT_____________________________________
Dry Run... Email Report disabled...
```

**Comment by diablo581** [comment]
Awesome man. No worries about the time. I saw that it had been a bit since you looked at all of this when I found the script.  I posted the first couple issues worried that it might be kind of abandoned, but you crushed them super quick.

I appreciate you looking at all of this stuff for me.  This script is going to be a big deal I think here in the future.

**Comment by JuggernautKY** [comment]
Long time listener, first time caller.... ;)

We are trying to use this script to deploy north of 4000 psks. I am not sure how I need to modify the ...psk.py file to allow this. We currently have 3000-4000 users in our PSK LDAP group and 5 static PSKs that are excluded by the script. However, when we run the script it is not adding anymore than the 1000. So, I am not sure if I need to change the limit=1000 to limit = 4900 or if it should already be paging. 

Please advise...

Any assistance is greatly appreciated!

**Comment by tmunzer** [comment]
Hi,

I moved this issue to #8 to have a better traking.
