### ISSUE TITLE
not able to create more than 1000 PSKs

### ISSUE THREAD

**Issue by tmunzer** [tmunzer/mist_ldap_sync#8]
Long time listener, first time caller.... ;)

We are trying to use this script to deploy north of 4000 psks. I am not sure how I need to modify the ...psk.py file to allow this. We currently have 3000-4000 users in our PSK LDAP group and 5 static PSKs that are excluded by the script. However, when we run the script it is not adding anymore than the 1000. So, I am not sure if I need to change the limit=1000 to limit = 4900 or if it should already be paging. 

Please advise...

Any assistance is greatly appreciated!

_Originally posted by @JuggernautKY in https://github.com/tmunzer/mist_ldap_sync/issues/7#issuecomment-1810361599_

**Comment by tmunzer** [comment]
Hi,

The pagination (and so the "limit" parameter) should not be an issue here, since it's only impacting the requests when retrieving the information from the Mist Cloud.
I'll add some logging features to the script so I can get a better view of what is happening. I'll let you know once it's available.

Thanks,
Thomas

**Comment by JuggernautKY** [comment]
My issue seems to be that there is a pagination issue with the LDAP query.

**Comment by diablo581** [comment]
I was thinking it might a limit in the LDAP query that only returns the first 1000 results?

**Comment by JuggernautKY** [comment]
I think this is the issue, I deleted a user from the cloud and the dry-run wants to put that same user back.

**Comment by JuggernautKY** [comment]
"auto_range" seems to be the resolution needed, I am just not sure where to add it.
https://ldap3.readthedocs.io/en/latest/connection.html

**Comment by tmunzer** [comment]
Thanks for the link. I added the parameter. Can you try it?

**Comment by JuggernautKY** [comment]
Yes, I will shortly.

**Comment by JuggernautKY** [comment]
The change doesn't appear to have resolved the issue. My dry-run output doesn't show that it would add the missing keys. I also read something that auto_range is defaulted to true in ldap3 now. It was in a release notes file.

**Comment by tmunzer** [comment]
thanks for the update. I'll try to replicate the issue on my side.
I'm also working on the code to add logging, and to optimise how the PSKs are created (to avoid to generate 1 API call for each PSK to create, which may be an issue for large number of users because Mist is limiting to 5000 API calls per hours)

**Comment by tmunzer** [comment]
Hi,

I applied a fix on this branch: [branch mistapi](https://github.com/tmunzer/mist_ldap_sync/tree/mistapi)

Can you give it a try.
It does not include the improvement on the API side, but it should work in your case.

Please note there is a new dependency to install (mistapi)

Thanks

**Comment by tmunzer** [comment]
I updated the script to fix the issue.
I also updated it to use the mistapi package which is fixing the case where there is more than 1000 PPSKs in Mist, and the script is now creating the PPSKs in bulk (100 PPSKs for each API request).

**Comment by JuggernautKY** [comment]
That seemed to resolve the issue. Thank you.

**Comment by tmunzer** [comment]
Thanks for the confirmation. I'll close the issue.

**Comment by JuggernautKY** [comment]
@tmunzer after implementing this code I am not able to send emails anymore when passcode creation is greater than 1k at least. I haven't tested much yet as I am just now discovering this and am out of time today to test it. Also, is there a way to run the script to re-email users their passcodes? An argument for all users as well as feeding an individual user to be re-emailed would be SUPER helpful.

**Comment by tmunzer** [comment]
Hi @JuggernautKY , can you create a new issue each time?
I created issue #10 to track this one
